### ISSUE TITLE
Infiltration Throws some twisted-internal error on map change

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#220]
This is probably due to some lack of cleanup. Either way, it does not cause issues.

**Comment by godwhoa** [comment]
Traceback:
```
2018-01-13 17:49:09+0530 [-] Generating map 'classicgen #149425617'...
2018-01-13 17:49:10+0530 [-] Map loaded successfully.
2018-01-13 17:49:29+0530 [-] Unhandled error in Deferred:
2018-01-13 17:49:29+0530 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/lib/python3.5/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/lib/python3.5/site-packages/twisted/internet/task.py", line 241, in __call__
	    d.addErrback(eb)
	  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/lib/python3.5/site-packages/twisted/internet/defer.py", line 332, in addErrback
	    errbackKeywords=kw)
	  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/lib/python3.5/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/lib/python3.5/site-packages/twisted/internet/task.py", line 236, in eb
	    d.errback(failure)
	builtins.AttributeError: 'NoneType' object has no attribute 'errback'
```

**Comment by godwhoa** [comment]
Hard to debug/reproduce it so removing it from milestone.
