### ISSUE TITLE
Python 2 does not have FIleNotFoundError

### ISSUE THREAD

**Issue by 5k1ttl3** [piqueserver/piqueserver#261]
Installed from git using the instructions in the Installation page of the Wiki

```
git clone https://github.com/piqueserver/piqueserver
virtualenv -p python2 venv
source venv/bin/activate
pip install -r requirements.txt
python setup.py install
```

When I run "piqueserver" I get the following:

```
(venv) root@localhost:/home/piqueserver# piqueserver
You are running piqueserver on Python 2.
This will be deprecated soon and it is recommended to upgrade to Python 3.
Please see https://github.com/piqueserver/piqueserver/wiki/Supported-Environments for more information.
Loading config from u'/root/.config/piqueserver/config.json'
Traceback (most recent call last):
  File "/home/piqueserver/venv/bin/piqueserver", line 11, in <module>
    load_entry_point('piqueserver==0.1.1', 'console_scripts', 'piqueserver')()
  File "/home/piqueserver/venv/local/lib/python2.7/site-packages/piqueserver-0.1.1-py2.7-linux-x86_64.egg/piqueserver/run.py", line 177, in main
    run_server()
  File "/home/piqueserver/venv/local/lib/python2.7/site-packages/piqueserver-0.1.1-py2.7-linux-x86_64.egg/piqueserver/run.py", line 87, in run_server
    server.run()
  File "/home/piqueserver/venv/local/lib/python2.7/site-packages/piqueserver-0.1.1-py2.7-linux-x86_64.egg/piqueserver/server.py", line 826, in run
    protocol_class(interface, config)
  File "/home/piqueserver/venv/local/lib/python2.7/site-packages/piqueserver-0.1.1-py2.7-linux-x86_64.egg/piqueserver/scripts/disco.py", line 40, in __init__
    protocol.__init__(self, *arg, **kw)
  File "/home/piqueserver/venv/local/lib/python2.7/site-packages/piqueserver-0.1.1-py2.7-linux-x86_64.egg/piqueserver/server.py", line 218, in __init__
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined
(venv) root@localhost:/home/piqueserver#
```

Should probably include platform information:
It's a Linode VPS machine running Ubuntu 17.10

**Comment by NotAFile** [comment]
Hey, a few notes:

 - Please be aware that the git version might contain bugs and is not intended to be run on production servers 
 - You are running on python2, which will be unsupported in two updates. It is recommended you run python3 instead
 - You are running piqueserver as root. This is not recommended for security reasons. We recommend you look up how to create a custom user instead.
- Yes, we have a bug here. It seem python2 does not have the `FileNotFoundError` and we never noticed, so it doesn't properly handle the error
- Before we solve this in master, you can fix this by just solving the core issue: you do not have a config directory. Run `piqueserver --copy-config` to create the default configuration.

**Comment by godwhoa** [comment]
Fixed it with https://github.com/piqueserver/piqueserver/commit/b2a22470b3a5c71c495cb2b5fc4e69166a01b3ba.
Will close if the fix works for you.

**Comment by godwhoa** [comment]
Tested on py2 doesn't crash now.
