### ISSUE TITLE
"god" in console with no arguments causes server crash

### ISSUE THREAD

**Issue by 5k1ttl3** [piqueserver/piqueserver#262]
The 'God' command should be used with an argument specifying which user to grant godmode to.

If you fail to specify a user, the server throws an error and fails to respond to any further commands (although the game still continues to run):

`god
2018-01-12 16:07:26+0000 [-] Command god failed with args: []
2018-01-12 16:07:26+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/process.py", line 291, in doRead
            return fdesc.readFromFD(self.fd, self.dataReceived)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
            callback(output)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/process.py", line 295, in dataReceived
            self.proc.childDataReceived(self.name, data)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
            self.protocol.dataReceived(data)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/piqueserver-0.1.1-py3.6-linux-x86_64.egg/piqueserver/console.py", line 89, in lineReceived
            result = commands.handle_input(self, line.decode())
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/piqueserver-0.1.1-py3.6-linux-x86_64.egg/piqueserver/commands.py", line 390, in handle_input
            return handle_command(connection, *parse_command(user_input))
          File "/home/skittle/piqueserver/venv/lib/python3.6/site-packages/piqueserver-0.1.1-py3.6-linux-x86_64.egg/piqueserver/commands.py", line 378, in handle_command
            traceback.print_exc(t)
          File "/usr/lib/python3.6/traceback.py", line 159, in print_exc
            print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
          File "/usr/lib/python3.6/traceback.py", line 100, in print_exception
            type(value), value, tb, limit=limit).format(chain=chain):
          File "/usr/lib/python3.6/traceback.py", line 497, in __init__
            capture_locals=capture_locals)
          File "/usr/lib/python3.6/traceback.py", line 332, in extract
            if limit >= 0:
        builtins.TypeError: '>=' not supported between instances of 'TypeError' and 'int'

`

**Comment by godwhoa** [comment]
@5k1ttl3 pushed the fix for it to `fix-god` branch. Can you test it out

**Comment by 5k1ttl3** [comment]
Just Tested. Works as expected now.
