### ISSUE TITLE
Friendlier error when no config is found

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#348]
Currently, it stack-traces that no config.json was found. This is confusing, especially with the json->toml switch,

**Comment by godwhoa** [comment]
Is this any better:
```
Traceback (most recent call last):
  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/bin/piqueserver", line 11, in <module>
    load_entry_point('piqueserver==0.1.3', 'console_scripts', 'piqueserver')()
  File "/home/pacninja/.local/share/virtualenvs/piqueserver-IhgHpnDk/lib/python3.5/site-packages/piqueserver-0.1.3-py3.5-linux-x86_64.egg/piqueserver/run.py", line 203, in main
ValueError: No config file found.
```

**Comment by NotAFile** [comment]
I don't think it should crash at all, tbh
