### ISSUE TITLE
Map Change Error.

### ISSUE THREAD

**Issue by Sonicscream** [piqueserver/piqueserver#432]
```
2019-01-09 15:17:36-0500 [-] Loading map '***'...
2019-01-09 15:17:36-0500 [-] Map loaded successfully.
2019-01-09 15:17:36-0500 [-] ***.***.***.*** disconnected
2019-01-09 15:17:36-0500 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python3.4/site-packages/piqueserver/run.py", line 205, in main
            server.run()
          File "/usr/lib64/python3.4/site-packages/piqueserver/server.py", line 842, in run
            reactor.run()
          File "/usr/lib64/python3.4/site-packages/twisted/internet/base.py", line 1243, in run
            self.mainLoop()
          File "/usr/lib64/python3.4/site-packages/twisted/internet/base.py", line 1252, in mainLoop
            self.runUntilCurrent()
        --- <exception caught here> ---
          File "/usr/lib64/python3.4/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/usr/lib64/python3.4/site-packages/piqueserver/server.py", line 457, in set_map_name
            self.set_map(self.map_info.data)
          File "/usr/lib64/python3.4/site-packages/piqueserver/scripts/flagreturn.py", line 43, in set_map
            protocol.set_map(self, map)
          File "/usr/lib64/python3.4/site-packages/pyspades/server.py", line 240, in set_map
            for connection in self.connections.values():
        builtins.RuntimeError: dictionary changed size during iteration
```

**Comment by Sonicscream** [comment]
A player leaving during for loop iterating breaks the game causing strange desync/random respawning.

**Comment by feikname** [comment]
I find it unlikely to be the cause, but please note Python 3.4 is no longer supported.

**Comment by feikname** [comment]
Also, which version and from where have you installed? e.g. `pip`, built latest `master`, etc.

**Comment by NotAFile** [comment]
I'm pretty sure this was fixed a while ago, yeah.

**Comment by Sonicscream** [comment]
Installed from pip. I'm guessing time to upgrade then? 😂

**Comment by NotAFile** [comment]
Depends on when you installed it from pip. We should leave this issue open until it is clear this is resolved.

**Comment by feikname** [comment]
You can find out your installed version with `pip show piqueserver`.

It should be version 1.0.0, otherwise, run `pip install --upgrade piqueserver`.

**Comment by NotAFile** [comment]
@feikname 1.0.0 hasn't been released though

**Comment by Sonicscream** [comment]
[x@x ~]$ pip show piqueserver
Name: piqueserver
Version: 0.1.3
Summary: Open-Source server implementation for Ace of Spades
Home-page: https://github.com/piqueserver/piqueserver
Author: noway421
Author-email: noway@2ch.hk
License: GNU General Public License v3
Location: /usr/lib64/python3.4/site-packages
Requires: Jinja2, Twisted, toml, six, pyenet, Cython, ipaddress, Pillow
Required-by:
[x@x ~]$

**Comment by NotAFile** [comment]
since we still have blockers on 1.0.0 iirc, we should backport the fix to the 0.x series

**Comment by feikname** [comment]
> @feikname 1.0.0 hasn't been released though

Oops, I meant 0.1.3, sorry!
