### ISSUE TITLE
Master Server Resolution failures aren't properly caught

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#480]
**Describe the bug**
When internet is unavailable but the master server connection is enabled, the name resolution failure leaks out of the master error handling, being printed as unhandled deferred with stack grace and without context.

**To Reproduce**
1. run server registered on master server without internet
2. see stacktrace

**Expected behavior**
The failure gets handled like all other master server failures

**Stack Trace or logs**
```
	Traceback (most recent call last):
	  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1421, in _inlineCallbacks
	    status.deferred.callback(getattr(e, "value", None))
	  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/nota/prj/piqueserver/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/nota/prj/piqueserver/piqueserver/server.py", line 409, in <lambda>
	    map_load_d.addCallback(lambda x: self._post_init())
	  File "/home/nota/prj/piqueserver/piqueserver/server.py", line 432, in _post_init
	    self.set_master()
	  File "/home/nota/prj/piqueserver/pyspades/server.py", line 337, in set_master
	    get_master_connection(self).addCallbacks(
	  File "/home/nota/prj/piqueserver/pyspades/master.py", line 105, in get_master_connection
	    connection = protocol.connect(MasterConnection, HOST, PORT, MASTER_VERSION)
	  File "/home/nota/prj/piqueserver/pyspades/protocol.py", line 95, in connect
	    peer = self.host.connect(enet.Address(host, port), channel_count,
	  File "enet.pyx", line 255, in enet.Address.__init__
	
	  File "enet.pyx", line 290, in enet.Address.host.__set__
	
	builtins.OSError: Resolution failure!
```

**Server (please complete the following information):**
 - OS/Version: linux
 - Piqueserver Version: 5171964

**Comment by utf-4096** [comment]
Fixed with the recent master refactoring https://github.com/piqueserver/piqueserver/blob/81143b31f7a45864af1650b3550126eba280076a/pyspades/master.py#L152
