### ISSUE TITLE
Improve error message when reading invalid bans.txt

### ISSUE THREAD

**Issue by yachmenka** [piqueserver/piqueserver#531]
The problem occurs both on the stable 0.1.3 version and on the git version. Archlinux hasn't this problem.
$ piqueserver
 
```
Loading config from '/home/user/.config/piqueserver/config.json'
2019-08-09T13:54:29+0300 [piqueserver.server#info] piqueserver started on Fri Aug  9 13:54:29 2019
2019-08-09T13:54:29+0300 [stderr#error] Traceback (most recent call last):
2019-08-09T13:54:29+0300 [stderr#error]   File "/home/user/git/piqueserver/venv/bin/piqueserver", line 11, in <module>
2019-08-09T13:54:29+0300 [stderr#error]     load_entry_point('piqueserver==0.1.3', 'console_scripts', 'piqueserver')()
2019-08-09T13:54:29+0300 [stderr#error]   File "/home/user/git/piqueserver/venv/lib/python3.7/site-packages/piqueserver-0.1.3-py3.7-linux-x86_64.egg/piqueserver/run.py", line 251, in main
2019-08-09T13:54:29+0300 [stderr#error]     server.run()
2019-08-09T13:54:29+0300 [stderr#error]   File "/home/user/git/piqueserver/venv/lib/python3.7/site-packages/piqueserver-0.1.3-py3.7-linux-x86_64.egg/piqueserver/server.py", line 976, in run
2019-08-09T13:54:29+0300 [stderr#error]     protocol_class(interface, config.get_dict())
2019-08-09T13:54:29+0300 [stderr#error]   File "/home/user/git/piqueserver/venv/lib/python3.7/site-packages/piqueserver-0.1.3-py3.7-linux-x86_64.egg/piqueserver/scripts/disco.py", line 45, in __init__
2019-08-09T13:54:29+0300 [stderr#error]     protocol.__init__(self, *arg, **kw)
2019-08-09T13:54:29+0300 [stderr#error]   File "/home/user/git/piqueserver/venv/lib/python3.7/site-packages/piqueserver-0.1.3-py3.7-linux-x86_64.egg/piqueserver/server.py", line 320, in __init__
2019-08-09T13:54:29+0300 [stderr#error]     self.bans.read_list(json.load(f))
2019-08-09T13:54:29+0300 [stderr#error]   File "/home/user/git/piqueserver/venv/lib/python3.7/site-packages/piqueserver-0.1.3-py3.7-linux-x86_64.egg/piqueserver/networkdict.py", line 18, in read_list
2019-08-09T13:54:29+0300 [stderr#error]     self[item[1]] = [item[0]] + item[2:]
2019-08-09T13:54:29+0300 [stderr#error] IndexError: list index out of range
```

**Comment by NotAFile** [comment]
I think this is a problem with the format of bans.txt

can you rename bans.txt and see if this fixes it?

**Comment by yachmenka** [comment]
Yes, this issue caused by incorrect format of bans.txt, i have pushed there an object of player without anything besides him ip address.
