### ISSUE TITLE
Empty name bug

### ISSUE THREAD

**Issue by Rakete175** [piqueserver/piqueserver#715]
**Describe the bug**
When a player attempts to enter piqueserver without a name, the server will print an IndexError and the player will be stuck as limbo player

**To Reproduce**
1. Join Game without a name
2. See error

**Expected behavior**
The server should allow players without names to join the game and change their name to "Deuce".

**Stack Trace or logs**
2022-02-23T19:44:05+0000 [stderr#error] Traceback (most recent call last):
2022-02-23T19:44:05+0000 [stderr#error]   File "/usr/local/lib/python3.8/site-packages/pyspades/protocol.py", line 170, in update
2022-02-23T19:44:05+0000 [stderr#error]     self.data_received(peer, event.packet)
2022-02-23T19:44:05+0000 [stderr#error]   File "/usr/local/lib/python3.8/site-packages/piqueserver/server.py", line 830, in data_received
2022-02-23T19:44:05+0000 [stderr#error]     ServerProtocol.data_received(self, peer, packet)
2022-02-23T19:44:05+0000 [stderr#error]   File "/usr/local/lib/python3.8/site-packages/pyspades/protocol.py", line 122, in data_received
2022-02-23T19:44:05+0000 [stderr#error]     connection.loader_received(packet)
2022-02-23T19:44:05+0000 [stderr#error]   File "/home/container/scripts/rakete_packetcounter.py", line 28, in loader_received
2022-02-23T19:44:05+0000 [stderr#error]     contained = load_client_packet(ByteReader(packet.data))
2022-02-23T19:44:05+0000 [stderr#error]   File "pyspades/packet.pyx", line 107, in pyspades.packet.load_client_packet
2022-02-23T19:44:05+0000 [stderr#error]   File "pyspades/packet.pyx", line 111, in pyspades.packet.load_contained_packet
2022-02-23T19:44:05+0000 [stderr#error]   File "pyspades/loaders.pyx", line 21, in pyspades.loaders.Loader.__init__
2022-02-23T19:44:05+0000 [stderr#error]   File "pyspades/contained.pyx", line 321, in pyspades.contained.ExistingPlayer.read
2022-02-23T19:44:05+0000 [stderr#error]   File "pyspades/common.pyx", line 88, in pyspades.common.decode
2022-02-23T19:44:05+0000 [stderr#error] IndexError: index out of range

**Server (please complete the following information):**
Latest piqueserver version

**Client (if relevant)**
Joining without a name works with all current clients.

**Additional context**
I have written a patch for it but I am not sure if thats the best way to solve it:
https://github.com/Rakete175/piqueserver/commit/c451ff81811871e8484092c5eb1d513946ddeb25

**Comment by NotAFile** [comment]
I would suggest fixing readString to make it return a real empty string instead and then make sure empty strings get caught by the existing invalid name mechanism.

**Comment by NotAFile** [comment]
Oh, I see the issue now: https://github.com/piqueserver/piqueserver/blob/master/pyspades/common.pyx#L88

This issue was introduced by the check for the unicode marker, which breaks for empty bytes.
