### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by DeathByDenim** [piqueserver/piqueserver#716]
**Describe the bug**
The MarkupSafe package introduced a breaking change in 2.1.x. It deprecated soft_unicode that piqueserver 1.0.0 depends on.

**To Reproduce**
1. Install piqueserver with `pip install -U piqueserver`
2. Run piqueserver
3. Piqueserver crashes with `ImportError: cannot import name 'soft_unicode' from 'markupsafe'`

**Expected behavior**
Not crash

**Stack Trace or logs**
```
Traceback (most recent call last):
  File "/opt/openspades/env/bin/piqueserver", line 11, in <module>
    load_entry_point('piqueserver==1.0.0', 'console_scripts', 'piqueserver')()
  File "/opt/openspades/env/lib/python3.9/site-packages/piqueserver/run.py", line 251, in main
    server.run()
  File "/opt/openspades/env/lib/python3.9/site-packages/piqueserver/server.py", line 974, in run
    protocol_class(interface, config.get_dict())
  File "/opt/openspades/env/lib/python3.9/site-packages/piqueserver/scripts/disco.py", line 45, in __init__
    protocol.__init__(self, *arg, **kw)
  File "/opt/openspades/env/lib/python3.9/site-packages/piqueserver/server.py", line 392, in __init__
    from piqueserver.statusserver import StatusServer
  File "/opt/openspades/env/lib/python3.9/site-packages/piqueserver/statusserver.py", line 24, in <module>
    from jinja2 import Environment, PackageLoader
  File "/opt/openspades/env/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/openspades/env/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/openspades/env/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/openspades/env/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/openspades/env/lib/python3.9/site-pac>
```

**Server (please complete the following information):**
 - OS/Version: Debian 11
 - Piqueserver Version: 1.0.0
 - Installation Method: pip

**Additional context**
Problem can be avoided by downgrading MarkupSafe to 2.0.1 using `pip install "MarkupSafe==2.0.1"`

**Comment by NotAFile** [comment]
This seems to be a bug in upstream jinja

**Comment by DeathByDenim** [comment]
Ah, so it is. There's even a pinned issue about this:
https://github.com/pallets/jinja/issues/1585

Seems to be something that can be fixed, but won't be because Jinja 2 is unsupported and one should use Jinja 3 according to that issue or making sure that one pins the dependencies as well as Jinja. See also https://github.com/pallets/jinja/issues/1585#issuecomment-1055670522

Anyway, not sure what the best way to deal with this is. I guess you could add MarkupSafe==2.0.1 to requirements.txt? I don't know enough about Jinja to know how much of a pain it would be to move to Jinja 3.

**Comment by NotAFile** [comment]
We don't have a lot of markup so jinja3 should be faily easy.

**Comment by nanovad** [comment]
I'm testing adjusting the dependency to be `Jinja2>=3.0.0`, which pulls in the latest version of Jinja2 (3.1.1). I don't see any immediate breakage. Looks like the only place it might be used is in `piqueserver/statusserver.py`, correct?

**Comment by NotAFile** [comment]
Yep, that's it.
