### ISSUE TITLE
afk.py rarely gives error

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#92]
might be a race condition

```
2017-06-06 14:57:34+0200 [-] Traceback (most recent call last):
2017-06-06 14:57:34+0200 [-]   File "/home/notafile/Documents/piqueserver/envpy2/local/lib/python2.7/site-packages/piqueserver-0.0.1-py2.7-linux-x86_64.egg/pyspades/protocol.py", line 164, in update
2017-06-06 14:57:34+0200 [-]     self.on_connect(peer)
2017-06-06 14:57:34+0200 [-]   File "/home/notafile/Documents/piqueserver/envpy2/local/lib/python2.7/site-packages/piqueserver-0.0.1-py2.7-linux-x86_64.egg/pyspades/protocol.py", line 108, in on_connect
2017-06-06 14:57:34+0200 [-]     connection.on_connect()
2017-06-06 14:57:34+0200 [-]   File "piqueserver/config/scripts/afk.py", line 98, in on_connect
2017-06-06 14:57:34+0200 [-]     if time_limit and not self.local:
2017-06-06 14:57:34+0200 [-] AttributeError: 'AFKConnection' object has no attribute 'local'

```

**Comment by noway** [comment]
self.local is set by server.py IIRC, need to check whether this attribute is actually set. It wasn't in certain revisions of pyspades

**Comment by damienflament** [comment]
The `local` flag is used on the `Player` object (in fact, the `Connection` I think) to check if the connection is done by a bot player. Many scripts rely on this flag to adapt their behavior (most of the time by doing nothing) for the bots.

The bot script comments tells to add the `local` property on the `Connection` object.  So, many server admins do it.

It's up to you to decide if this property must be added to the _piqueserver_ source code, or if the scripts should check the property existence before checking its value !

**Comment by NotAFile** [comment]
This usually works though, so it must be set somewhere. I think setting undocumented plugin specific flags in core files is a bad precedent, but on the other hand since this has become a kind of standard it's probably best to embrace it and add it to the documentation.

**Comment by 1AmYF** [comment]
The local flag was added here https://github.com/piqueserver/piqueserver/commit/52ac0ac7a582d2f42d3eb9f4a8c6c86b50f03dbf by me with the idea to allow instant usage of bot scripts, without the need to adapt any further files for it (as also mentioned in #81). All variations of bots in Ace of Spades (known to me) are based on basicbot.py made by Hompy (his dropbox is not available anymore, so file is here: https://pastebin.com/54jYmPPJ). It was not a part of pyspades, so that suggested addition of the local flag was also not present in piqueserver before.
I've done a log search on *Sauerkraut looking for that AttributeError, it never occured there, however it's still running on pyspades (with local flag and adapted afk.py), and not on piqueserver yet.

**Comment by NotAFile** [comment]
This only happened once so far, I guess you'd have to see if it's actually an issue. Either way it would probably be good to fix it.

**Comment by NotAFile** [comment]
This should be fixed back when we made bots native
